version: '3.8'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      timeout: 10s
      retries: 10
    restart: always
    networks:
      - network

  backend:
    ports:
      - "8080:8080"
    build:
      dockerfile: backend/Dockerfile
      context: .
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - network

networks:
  network:
    driver: bridge
