version: '3.8'
services:
  mysql:
    ports:
      - "3306:3306"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      timeout: 10s
      retries: 10
    restart: always
    networks:
      - network

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    depends_on:
      - mysql
    networks:
      - network

networks:
  network:
    driver: bridge
